### ISSUE TITLE
check itemFragment is not null

### ISSUE THREAD

**Issue by 102Rudy** [K1ola/Android-DZ1#13]
Когда может  выполниться это условие, и может ли вообще оно выполниться?

https://github.com/K1ola/Android-DZ1/blob/09c8b359d4bbfbdaff6bc474d8d7e47db7b0dca4/app/src/main/java/com/example/myapplication/MainActivity.java#L30

**Comment by K1ola** [comment]
Действительно лишняя проверка, условие никогда не выполнится. Убрала.
