### ISSUE TITLE
ArrayList -> List

### ISSUE THREAD

**Issue by 102Rudy** [K1ola/Android-DZ1#6]
При объявлении переменной лучше использовать абстракцию **List**, вместо конкретной реализации **ArrayList**

https://github.com/K1ola/Android-DZ1/blob/24147d1002d738730bf97feb114e3cd3d7f36747/app/src/main/java/com/example/myapplication/ListFragment.java#L24

**Comment by 102Rudy** [comment]
также, инициализировать лист здесь - не очень хорошо
Лучше в onCreate или onCreateView

**Comment by K1ola** [comment]
а если инициализировать в конструкторе ListFragment()?
