### ISSUE TITLE
Fragment constructor

### ISSUE THREAD

**Issue by 102Rudy** [K1ola/Android-DZ1#7]
Конструктор фрагмента лучше оставить пустым.
В данном случае это не так страшно, но лучше сразу приучить себя ничего не делать в конструкторе фрагмента/активити

А лист лучше инициализировать в другом месте

https://github.com/K1ola/Android-DZ1/blob/24147d1002d738730bf97feb114e3cd3d7f36747/app/src/main/java/com/example/myapplication/ListFragment.java#L27

**Comment by K1ola** [comment]
А почему лучше не трогать конструктор фрагмента/активити?
